QUESTION 2

In [26]:
import numpy as np

a)

In [27]:
x = np.array([-1, 3, 2])
b = np.array([4, -1, 6])
M1= np.array((x, b))
print(M1)

[[-1  3  2]
 [ 4 -1  6]]


In [28]:
x = np.array([-1, 3, 2, 4, -1, 6])
M1= np.array(x)
print(M1)

[-1  3  2  4 -1  6]


b)

In [29]:
A = np.array([[1, 4, 0],
              [3, 7, 5],
              [2, 8, -2]])

In [30]:
M1 = A[[2,0], :2]
M2 = A[0] + A[1] - A[2]
M3 = A[1:, 1:]
M4 = A[[0,2], :][:, [0,2]]
M5 = A[::-1]
M6 = A[:, ::-1]
M7 = A.T
M8 = A.flatten()
print(M1,M2,M3,M4,M5,M6,M7,M8)

[[2 8]
 [1 4]] [2 3 7] [[ 7  5]
 [ 8 -2]] [[ 1  0]
 [ 2 -2]] [[ 2  8 -2]
 [ 3  7  5]
 [ 1  4  0]] [[ 0  4  1]
 [ 5  7  3]
 [-2  8  2]] [[ 1  3  2]
 [ 4  7  8]
 [ 0  5 -2]] [ 1  4  0  3  7  5  2  8 -2]


QUESTION 5 Create a NumPy array of

In [31]:
import numpy as np

a) positive integers less than 1000 that are divisible by 3. The find the sum of that array

In [36]:
arr_a = np.arange(3, 1000, 3)
sum_a = np.sum(arr_a)
print(arr_a, sum_a)

[  3   6   9  12  15  18  21  24  27  30  33  36  39  42  45  48  51  54
  57  60  63  66  69  72  75  78  81  84  87  90  93  96  99 102 105 108
 111 114 117 120 123 126 129 132 135 138 141 144 147 150 153 156 159 162
 165 168 171 174 177 180 183 186 189 192 195 198 201 204 207 210 213 216
 219 222 225 228 231 234 237 240 243 246 249 252 255 258 261 264 267 270
 273 276 279 282 285 288 291 294 297 300 303 306 309 312 315 318 321 324
 327 330 333 336 339 342 345 348 351 354 357 360 363 366 369 372 375 378
 381 384 387 390 393 396 399 402 405 408 411 414 417 420 423 426 429 432
 435 438 441 444 447 450 453 456 459 462 465 468 471 474 477 480 483 486
 489 492 495 498 501 504 507 510 513 516 519 522 525 528 531 534 537 540
 543 546 549 552 555 558 561 564 567 570 573 576 579 582 585 588 591 594
 597 600 603 606 609 612 615 618 621 624 627 630 633 636 639 642 645 648
 651 654 657 660 663 666 669 672 675 678 681 684 687 690 693 696 699 702
 705 708 711 714 717 720 723 726 729 732 735 738 74

b) the geometric sequence 1, 3, 32, · · · , 310. Then find the sum of that sequence.

In [35]:
arr_b = 3 ** np.arange(0, 11)
sum_b = np.sum(arr_b)
print(arr_b, sum_b)

[    1     3     9    27    81   243   729  2187  6561 19683 59049] 88573


QUESTION 7

a)

In [61]:
A = np.random.randint(1, 6, size=(3,4))
print(A)

[[4 5 4 3]
 [3 5 1 5]
 [2 3 5 1]]


b)

In [62]:
row = np.array([1, 2, 3, 4])
B = np.tile(row, (20, 2))
print(B)

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]]


c)

In [63]:
C = np.diag(np.arange(1, 11))
print(C)

[[ 1  0  0  0  0  0  0  0  0  0]
 [ 0  2  0  0  0  0  0  0  0  0]
 [ 0  0  3  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  6  0  0  0  0]
 [ 0  0  0  0  0  0  7  0  0  0]
 [ 0  0  0  0  0  0  0  8  0  0]
 [ 0  0  0  0  0  0  0  0  9  0]
 [ 0  0  0  0  0  0  0  0  0 10]]


d)

In [64]:
block1 = np.ones((2, 2))
block2 = 2*np.ones((3, 3))
D = np.block([
    [block1, np.zeros((2, 3))],
    [np.zeros((3,2)), block2]
])
print(D)

[[1. 1. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [0. 0. 2. 2. 2.]
 [0. 0. 2. 2. 2.]
 [0. 0. 2. 2. 2.]]


QUESTION 9

In [38]:
import sympy as sym
x, y = sym.symbols('x y')

a)

In [40]:
expr1 = x**2*(x+y) + y**2*(y - x**2) + x
ans1 = sym.expand(expr1)
ans1

x**3 - x**2*y**2 + x**2*y + x + y**3

In [70]:
expr2 = sym.cos(x)**2 - sym.tan(x)**2 + sym.sin(x)**2
ans2 = sym.simplify(expr2)
ans2

1 - tan(x)**2

In [71]:
expr3 = (x-2)**3 * sym.exp(2*x) + x*(sym.exp(2*x)-1)**2
ans3 = sym.expand(expr3)
ans3

x**3*exp(2*x) - 6*x**2*exp(2*x) + x*exp(4*x) + 10*x*exp(2*x) + x - 8*exp(2*x)

In [72]:
expr4 = (2*x**2 + y**2)*(x + y**2 + 3)
ans4 = sym.collect(sym.expand(expr4), y)
ans4

2*x**3 + 6*x**2 + y**4 + y**2*(2*x**2 + x + 3)

In [73]:
expr5 = sym.exp(2*x)*(x**2 - 1) + (x - sym.exp(x))**2*sym.exp(x) + sym.exp(-x)*(x + sym.exp(2*x))
ans5 = sym.collect(sym.expand(expr5), sym.exp(x))
ans5

x*exp(-x) + (x**2 + 1)*exp(x) + (x**2 - 2*x - 1)*exp(2*x) + exp(3*x)

b)

In [74]:
pf1 = sym.apart((-4*x + 8)/(x**2 + 6*x + 8))
pf1

-12/(x + 4) + 8/(x + 2)

In [75]:
pf2 = sym.apart((6*x - 5)/(4*x**2 - 4*x + 1))
pf2

3/(2*x - 1) - 2/(2*x - 1)**2

In [76]:
pf3 = sym.apart((4*x**2 + 2*x - 4)/(4*x**2 - 4*x + 1))
pf3

1 + 3/(2*x - 1) - 2/(2*x - 1)**2

c)

Show that the following trigonometric identities are valid.

    i. sin(x + y) ≡ sin(x) cos(y) + cos(x) sin(y)

In [79]:
sym.simplify(sym.sin(x+y) - (sym.sin(x)*sym.cos(y) + sym.cos(x)*sym.sin(y)))

0

ii. cos(x + y) ≡ cos(x) cos(y) − sin(x) sin(y)

In [78]:
sym.simplify(sym.cos(x+y) - (sym.cos(x)*sym.cos(y) - sym.sin(x)*sym.sin(y)))

0

iii. sin(x) cos(y) ≡ 1/2 (sin(x + y) + sin(x − y))

In [80]:
sym.simplify(sym.sin(x)*sym.cos(y) - sym.Rational(1,2)*(sym.sin(x+y) + sym.sin(x-y)))

0

iv. cos(3x) = 4 cos3(x) − 3 cos(x)

In [81]:
sym.simplify(sym.cos(3*x) - (4*sym.cos(x)**3 - 3*sym.cos(x)))

0

QUESTION 10

In [82]:
import sympy as sym
x = sym.symbols('x')

(a) 

In [83]:
lim_a = sym.limit(sym.sin(x)/x, x, 0)
lim_a

1

b)

In [84]:
lim_b = sym.limit((sym.exp(x) + x)**(1/x), x, 0)
lim_b

exp(2)

c)

In [85]:
lim_c = sym.limit((x**2 - 1)/(x**3 -1), x, 1)
lim_c

2/3

d)

In [86]:
lim_d = sym.limit((1 - sym.log(x))/sym.exp(1/x), x, 0, '+')
lim_d

0

e)

In [87]:
lim_e = sym.limit(sym.sqrt(x**2 + x) - x, x, sym.oo)
lim_e

1/2

f)

In [88]:
lim_f = sym.limit(1/x - sym.log(x), x, 0, '+')
lim_f

oo

QUESTION 11

In [2]:
import sympy as sym
x, y, t = sym.symbols('x y t')

a)

In [3]:
expr_a = 5*x**3**t + t**2*y - sym.exp(-t)*sym.cos(t)
ans_a = sym.diff(expr_a, t)
ans_a

5*3**t*x**(3**t)*log(3)*log(x) + 2*t*y + exp(-t)*sin(t) + exp(-t)*cos(t)

b)

In [11]:
expr_b = sym.sin(3*x)**3 + sym.cos(x)
ans_b = sym.diff(expr_b, x, 3)
ans_b = ans_b.subs(x, sym.pi/3)
ans_b

-162 + sqrt(3)/2

c)

In [5]:
expr_c = sym.sin(x)*sym.cos(y)
ans_c = sym.diff(expr_c, x, y)
ans_c

-sin(y)*cos(x)

d)

In [6]:
ans_d = sym.integrate(sym.atan(x), (x, sym.pi/4, sym.pi/2))
ans_d

-log(1 + pi**2/4)/2 - pi*atan(pi/4)/4 + log(pi**2/16 + 1)/2 + pi*atan(pi/2)/2

e)

In [7]:
ans_e = sym.integrate(x*sym.sqrt(1-x**2), x)
ans_e

x**2*sqrt(1 - x**2)/3 - sqrt(1 - x**2)/3

f)

In [8]:
ans_f = sym.integrate(x*sym.sqrt(1-x**2), (x, sym.Rational(1,2), 1))
ans_f

sqrt(3)/8

g)

In [10]:
ans_g = sym.N(sym.integrate(sym.sin(x)/x, (x, 1, 2)))
ans_g

0.659329906435512

QUESTION 15 Solve

In [12]:
import sympy as sym
x = sym.symbols('x')

a) 6x3 − 25x2 + 34x − 15 = 0

In [13]:
expr_a = 6*x**3 - 25*x**2 + 34*x - 15
ans_a = sym.solve(expr_a, x)
ans_a

[1, 3/2, 5/3]

b) 5ex − e2x = 6

In [14]:
expr_b = 5*sym.exp(x) - sym.exp(2*x) - 6
ans_b = sym.solve(expr_b, x)
ans_b

[log(2), log(3)]

c) cos 3x − 2 cos 2x + 2 cos x = 1

In [15]:
expr_c = sym.cos(3*x) - 2*sym.cos(2*x) + 2*sym.cos(x) - 1
ans_c = sym.solve(expr_c, x)
ans_c

[0, -2*pi/3, -pi/3, pi/3, 2*pi/3]

QUESTION 16 Solve the following system of equations

In [16]:
import sympy as sym
x, y, z, t, r, s = sym.symbols('x y z t r s')

a) 10x + 12y + 16t = 0, 5x − y = 13t for

i) x and y in terms of t.

In [17]:
eq1 = sym.Eq(10*x + 12*y + 16*t, 0)
eq2 = sym.Eq(5*x - y, 13*t)
sol_a1 = sym.solve([eq1, eq2], (x,y))
sol_a1

{x: 2*t, y: -3*t}

ii) t and y in terms of x.

In [18]:
sol_a2 = sym.solve([eq1, eq2], (t, y))
sol_a2

{t: x/2, y: -3*x/2}

iii) t and x in terms of y.

In [19]:
sol_a3 = sym.solve([eq1, eq2], (t, x))
sol_a3

{t: -y/3, x: -2*y/3}

b) rx + sy + tz = 1, 2rx + sy − tz = 2,−rx + 2sy − 2tz = 3 for

i) x, y and z in terms of r, s and t.

In [21]:
eq1 = sym.Eq(r*x + s*y + t*z, 1)
eq2 = sym.Eq(2*r*x + s*y - t*z, 2)
eq3 = sym.Eq(-r*x + 2*s*y - 2*t*z, 3)
sol_b1 = sym.solve([eq1, eq2, eq3], (x, y, z))
sol_b1

{x: 1/(5*r), y: 6/(5*s), z: -2/(5*t)}

ii) r, s and t in terms of x, y and z.

In [23]:
sol_b2 = sym.solve([eq1, eq2, eq3], (r, s, t))
sol_b2

{r: 1/(5*x), s: 6/(5*y), t: -2/(5*z)}